require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Nudje' do
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text', :modular_headers => true

  # pod 'react-native-image-crop-picker', :path => '../node_modules/react-native-image-crop-picker/ios'

  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'NudjeTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'Nudje-tvOS' do
  # Pods for Nudje-tvOS

  target 'Nudje-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
